name: CLA

on: [pull_request]

jobs:
  checkCLA:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Autoclose Pull Request
#      uses: fotise/test-typescript-container-action@master
#      with:
#        github-token: ${{ secrets.GITHUB_TOKEN }}
#        message: Pull Request is not allowed on this repository
    - name: Autoclose Pull Request
      uses: fotise/pull-request-autoclose-action@releases/v0.0.1
      with:
        milliseconds: 1000
    
