name: test action integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: TypeScript Container Action Template
      uses: kevinpollet/typescript-container-action-template@v1
      with:
        # Name to greet
        name: aaaaaaaaaaaaaa
    
